<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit PO for Supplier  Warehouse  Ware_ca2acd</name>
   <tag></tag>
   <elementGuidId>5282f627-e770-4e95-b356-db7a9c3bfd10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#po-submit-modal-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='po-submit-modal-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe1aa469-abfe-4f03-b5dc-7bad960a3a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>po-submit-modal-1</value>
      <webElementGuid>294d368d-cb22-4f4f-8da5-187a0962bf7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bdcf4c9f-3600-41a9-9f40-bc93c40885b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>07966b89-935a-441d-ae73-afb9a0cb50a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>locationModalLabel</value>
      <webElementGuid>94c382eb-0512-4b89-b2bd-2931baeec9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal show</value>
      <webElementGuid>41d8fe92-7ddc-4745-83bc-62e69d0ace61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a31569bc-1986-4497-bccb-770b4942b346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit PO for: Supplier  Warehouse: * Warehouse Deliver To: *  Bill To: *          Close 
                                Submit
                        </value>
      <webElementGuid>e3acdbab-eda4-4963-a53f-e81e44de5253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;po-submit-modal-1&quot;)</value>
      <webElementGuid>1426717d-1472-4818-8ad4-c0f210e0f701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='po-submit-modal-1']</value>
      <webElementGuid>9162293b-3e4f-4f81-82f0-4fe0ffc71eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='po-form']/div/div[2]/div</value>
      <webElementGuid>32241a99-fb16-4be2-af95-f38b8b8fad46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[2]</value>
      <webElementGuid>d0b4165c-ed5b-4faf-94e5-69859978bcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[3]/following::div[2]</value>
      <webElementGuid>46338d25-6b46-4ad2-a389-d5acb84a1705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>9e3cbc2a-b53f-43ba-95f4-813835d1f884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'po-submit-modal-1' and (text() = 'Submit PO for: Supplier  Warehouse: * Warehouse Deliver To: *  Bill To: *          Close 
                                Submit
                        ' or . = 'Submit PO for: Supplier  Warehouse: * Warehouse Deliver To: *  Bill To: *          Close 
                                Submit
                        ')]</value>
      <webElementGuid>318245fb-cdc9-4529-839e-7a9d42cbd6cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
