<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product</name>
   <tag></tag>
   <elementGuidId>bda45463-a392-4e29-9623-1cd206f8bb7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c994a1a1-4b41-428b-aca0-ac0e2615beeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f195aebb-59d2-41ec-9155-f28dc3b2e39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validity.valid||(value='')</value>
      <webElementGuid>ec91d584-061a-49aa-b34d-0fe24b10836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>1a748af8-0f35-4492-8650-e9fa384cb427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>f722a245-7308-4fea-ad49-83160f1c5ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_qty</value>
      <webElementGuid>0e296eff-db18-4652-9453-5d00d5c7fb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>####</value>
      <webElementGuid>2b2beb84-4bdb-4577-a8b1-7926af800b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9791f8bc-5da1-48af-ae56-4b27376b5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e456a71-5b68-4977-bb10-0163adfe6dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_qty&quot;)</value>
      <webElementGuid>fa7f95e1-a47a-4d10-96b5-764041c19c8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_qty']</value>
      <webElementGuid>8c335a06-1715-47a6-b851-32a2a0b41ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='po-form']/div/div/div/div/div[6]/div/div[9]/input</value>
      <webElementGuid>1e726f65-737b-4f8c-9744-7b436ef09734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[9]/input</value>
      <webElementGuid>22d2ac61-1f5c-4969-ba60-3fcf17736e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product' and @id = 'order_qty' and @placeholder = '####']</value>
      <webElementGuid>819646e9-2fb6-4711-a655-7943157a5dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
