<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product_1</name>
   <tag></tag>
   <elementGuidId>3ce4c128-c1a9-4378-941b-97114d0fffdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28df71cf-c1f8-4ae8-b6ab-f1e3d2d7218a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>73aa0e04-1ae9-4021-b344-1fe0827756a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validity.valid||(value='')</value>
      <webElementGuid>89f24147-0e52-412f-bbb2-1a6651ce51b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47e887a5-5859-4030-a98d-5a6256b29574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>8090896a-45db-47fe-b955-72448d3e08bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>0e5c8c13-7d23-46af-a56f-4d025d7d9fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>a3aedc70-5357-4734-ac36-25e89d8c8dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$##.##</value>
      <webElementGuid>9fab2517-3b0c-4381-88db-5c2bebe15410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>897f567a-a052-4118-a4b4-d434fe4e9003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;price&quot;)</value>
      <webElementGuid>29f503ca-81ba-4d0a-9685-f223aecc2c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='price']</value>
      <webElementGuid>40acc6e0-64a1-4d3e-9efa-054296c8a12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='po-form']/div/div/div/div/div[6]/div/div[10]/input</value>
      <webElementGuid>b27497d3-9dfe-484e-9f44-50e0c63be051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>acaa4008-e003-4b52-a6ca-14005fc05a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'product' and @id = 'price' and @placeholder = '$##.##']</value>
      <webElementGuid>e9ef3d89-b7d9-470d-abba-80dd1f93e4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
