<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Super System  Admin system.admintest.com_7d7112</name>
   <tag></tag>
   <elementGuidId>76fa5714-7ab3-4a3e-a7f3-4c2d41861b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav/div[2]/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>d6320554-227c-4b36-b1e6-84abdce2bf90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>de2edc6c-b079-49d8-a445-eca7731ecca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Super System  Admin system.admin@test.com  Home  Purchase Orders  Create Shopping List Summary Marketplace Invoices  Inbound  Receiving / Put Away Non-PO  Outbound  Dispatch  Transfer Orders  Create Approve Picking Receive  Inventory Management  Inventory Levels Bin to Bin  Cycle Count  Manual Reconciliation  Reports  Inventory Orders Receivings Dispatch Non-PO Non-PO Suppliers  Settings  My Items My Recipes My Modifiers My Suppliers My Warehouses My Companies My Locations My Orders My Invoices Users My Config</value>
      <webElementGuid>522eb1e3-3cf4-4457-8f8d-b1488b8c41e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebar-body justify-content-between ps&quot;]/ul[@class=&quot;nav&quot;]</value>
      <webElementGuid>db5a1b04-949e-4582-bdb2-afa8a65ffbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/div[2]/ul</value>
      <webElementGuid>97eb844c-8f35-4c4a-870c-4479d185c246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::ul[1]</value>
      <webElementGuid>7871bc7d-a31d-47c2-8c06-87c6120ef3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>250654a8-667f-4727-9cd9-7ae96ddde58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Super System  Admin system.admin@test.com  Home  Purchase Orders  Create Shopping List Summary Marketplace Invoices  Inbound  Receiving / Put Away Non-PO  Outbound  Dispatch  Transfer Orders  Create Approve Picking Receive  Inventory Management  Inventory Levels Bin to Bin  Cycle Count  Manual Reconciliation  Reports  Inventory Orders Receivings Dispatch Non-PO Non-PO Suppliers  Settings  My Items My Recipes My Modifiers My Suppliers My Warehouses My Companies My Locations My Orders My Invoices Users My Config' or . = 'Super System  Admin system.admin@test.com  Home  Purchase Orders  Create Shopping List Summary Marketplace Invoices  Inbound  Receiving / Put Away Non-PO  Outbound  Dispatch  Transfer Orders  Create Approve Picking Receive  Inventory Management  Inventory Levels Bin to Bin  Cycle Count  Manual Reconciliation  Reports  Inventory Orders Receivings Dispatch Non-PO Non-PO Suppliers  Settings  My Items My Recipes My Modifiers My Suppliers My Warehouses My Companies My Locations My Orders My Invoices Users My Config')]</value>
      <webElementGuid>512beb4c-70bb-4acf-aa33-342ca8fd6d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
