<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e581e234-c4b7-4529-9981-857ba6bd86ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a76e68fd-f5bf-4603-9b4a-06931f1af1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://allec.metabaseapp.com/embed/dashboard/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjQ0fSwicGFyYW1zIjp7fX0.PMhpCoFyEvFBRooMAP6-9d_RjSyjkEXFgVCh-_QKLWo#bordered=false&amp;titled=true</value>
      <webElementGuid>1ef05531-5c75-4bd1-bbac-9edca17744d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>516c8b11-afc4-41ec-9b8d-f2f90f694b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-content&quot;]/div[1]/div[@class=&quot;row&quot;]/iframe[1]</value>
      <webElementGuid>962b38df-86b2-4738-b0cb-f4d2ff0379df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/iframe</value>
      <webElementGuid>c68fbe97-f6ff-4559-b570-d3a68fd081d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ff980cd5-a9fc-46be-b7d2-2d8424e5755b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://allec.metabaseapp.com/embed/dashboard/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjQ0fSwicGFyYW1zIjp7fX0.PMhpCoFyEvFBRooMAP6-9d_RjSyjkEXFgVCh-_QKLWo#bordered=false&amp;titled=true']</value>
      <webElementGuid>9d1c1123-9977-4f8a-b7e9-cce9507c595d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
