<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_InventoryManagement</name>
   <tag></tag>
   <elementGuidId>24bc88ca-0b45-430b-ae43-6c0ca9676f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sidebar-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c4c0be1-e819-4a17-a9dd-677b59d9ceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-header</value>
      <webElementGuid>71a18493-223f-4617-8c29-b80db85c942b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                InventoryManagement   </value>
      <webElementGuid>1e8ccd7b-4474-4cc3-9401-be360874a708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;sidebar&quot;]/div[@class=&quot;sidebar-header&quot;]</value>
      <webElementGuid>11db9e8a-1991-4886-9629-b79b00f9db2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/div</value>
      <webElementGuid>3a22b52f-d81d-4fca-97c1-0c0fbc56c40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::div[2]</value>
      <webElementGuid>a015e920-f079-44e5-89c9-f1d0af6a4261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div</value>
      <webElementGuid>9e7393be-a81d-4154-8bfa-b36f921b98ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                InventoryManagement   ' or . = '
                InventoryManagement   ')]</value>
      <webElementGuid>6baba0e3-2af6-4222-8a89-c8fedb10fe6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
